nnrss/views.py
"""Module containing main views for web client"""
import datetime as dt

from flask import Blueprint, Response, flash, render_template, request, session, url_for
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.exceptions import abort
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import redirect

from nnrss.background_update import BACKGROUND_TASK
from nnrss.database import RssHandler
from nnrss.decorators import (
    admin_required,
    guest_required,
    login_required,
    registration_enabled,
)
from nnrss.forms import (
    AddFeedForm,
    ExportForm,
    ImportForm,
    LoginForm,
    RegistrationForm,
    SettingsForm,
)
from nnrss.models import User
from nnrss.opml import OPMLWriter
from nnrss.thread_import import ImportThread

DEFAULT_WEB = Blueprint("default_web", __name__)


@DEFAULT_WEB.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html", error=error), 404


@DEFAULT_WEB.route("/")
@login_required
def index():
    category = request.args.get("category", None)
    handler = RssHandler()
    if category:
        entries = handler.get_unread_entries(session["logged_in"], category)
        categories = None
    else:
        entries = handler.get_unread_entries(session["logged_in"])
        categories = handler.get_all_categories(session["logged_in"])
    return render_template(
        "unread_entries.html",
        entries=entries,
        category_name=category,
        categories=categories,
    )


@DEFAULT_WEB.route("/list")
@login_required
def feed_list():
    category = request.args.get("category", None)
    handler = RssHandler()
    if category:
        feeds = handler.get_feeds_from_category(session["logged_in"], category)
        categories = None
    else:
        feeds = handler.get_feeds(session["logged_in"])
        categories = handler.get_all_categories(session["logged_in"])
    return render_template(
        "feed_list.html",
        feeds=feeds,
        categories=categories,
        category_name=category,
    )


@DEFAULT_WEB.route("/add", methods=["GET", "POST"])
@login_required
def add_feed():
    form = AddFeedForm(request.form)
    if request.method == "POST" and form.validate():
        handler = RssHandler()
        feed_added = handler.add_feeds(
            [form.url.data], session["logged_in"], [form.category.data]
        )
        if not feed_added or feed_added is None:
            flash("Not a valid feed URL", "error")
        else:
            flash("Feed {} added!".format(form.url.data), "info")
    return render_template("feed_add.html", form=form)


@DEFAULT_WEB.route("/feed/<int:feed_id>")
@login_required
def view_feed_entries(feed_id=None):
    if feed_id is None:
        return "Enter id after URL", 400
    page = int(request.args.get("page", 1))
    handler = RssHandler()
    if not handler.feed_exists(feed_id):
        return abort(404, description="Feed not found")
    entries = handler.get_entries_by_feed_id(feed_id, session["logged_in"])
    selected_feed = handler.get_feed_without_details(feed_id, session["logged_in"])
    return render_template(
        "entries_list.html",
        entries=entries.paginate(page=page),
        feed=selected_feed,
    )


@DEFAULT_WEB.route("/feed/<int:feed_id>/unread")
@login_required
def view_feed_entries_unread(feed_id=None):
    if feed_id is None:
        return "Enter id after URL", 400
    page = int(request.args.get("page", 1))
    handler = RssHandler()
    if not handler.feed_exists(feed_id):
        return abort(404, description="Feed not found")
    entries = handler.get_unread_entries_by_feed_id(feed_id, session["logged_in"])
    selected_feed = handler.get_feed_without_details(feed_id, session["logged_in"])
    return render_template(
        "entries_list_unread.html",
        entries=entries.paginate(page=page),
        feed=selected_feed,
    )


@DEFAULT_WEB.route("/feed/<int:feed_id>/update", methods=["POST"])
@login_required
def update_feed_entries(feed_id=None):
    if feed_id is None:
        return "Enter id after URL", 400
    handler = RssHandler()
    if handler.update_feed(feed_id, session["logged_in"]):
        flash("Feed updated!", "info")
    else:
        return abort(404, description="Feed not found")
    return redirect(url_for("default_web.view_feed_entries", feed_id=feed_id))


@DEFAULT_WEB.route("/feed/<int:feed_id>/set_read")
@login_required
def set_read_entry(feed_id=None, entry_id=None):
    if feed_id is None:
        return "feed_id URL part missing", 400
    entry_id = request.args.get("entry_id")
    if entry_id is None:
        return "entry_id parameter missing", 400
    handler = RssHandler()
    ok, link = handler.set_read_entry(feed_id, entry_id, session["logged_in"])
    if ok:
        return redirect(link, code=302)
    else:
        return abort(404, description="Feed not found")


@DEFAULT_WEB.route("/feed/<int:feed_id>/remove", methods=["GET", "POST"])
@login_required
def remove_feed(feed_id=None):
    handler = RssHandler()
    if request.method == "POST":
        if feed_id is None:
            return "Enter id after URL"
        if handler.remove_feed(feed_id, session["logged_in"]):
            flash("Feed removed!", "info")
        else:
            return abort(404, description="Feed not found")
        return redirect(url_for("default_web.index"))
    selected_feed = handler.get_feed_without_details(feed_id, session["logged_in"])
    return render_template("delete_confirm.html", the_feed=selected_feed)


@DEFAULT_WEB.route("/admin")
@admin_required
def admin_index(feed_id=None):
    handler = RssHandler()
    users = handler.get_users()
    feed_count = [handler.get_feeds_count(user.username) for user in users]
    return render_template(
        "admin_panel.html", users=handler.get_users(), feed_count=feed_count
    )


@DEFAULT_WEB.route("/login", methods=["GET", "POST"])
@guest_required
def login():
    form = LoginForm(request.form)
    if request.method == "POST" and form.validate():
        handler = RssHandler()
        password = handler.get_user_password(form.username.data)
        if password is not None and check_password_hash(password, form.password.data):
            session["logged_in"] = form.username.data
            session.permanent = True
            flash("Logged in", "info")
        else:
            flash("Wrong credentials", "error")
        return redirect(url_for("default_web.index"))
    return render_template("login.html", form=form)


@DEFAULT_WEB.route("/logout")
@login_required
def logout():
    session.pop("logged_in", None)
    return redirect(url_for("default_web.index"))


@DEFAULT_WEB.route("/register", methods=["GET", "POST"])
@registration_enabled
@guest_required
def register():
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate():
        handler = RssHandler()
        new_user = User(
            form.username.data,
            generate_password_hash(form.password.data, method="pbkdf2:sha512"),
        )
        is_ok = handler.add_user(new_user)
        if is_ok:
            flash("Registered", "info")
            BACKGROUND_TASK.add_new_user_job(form.username.data)
            return redirect(url_for("default_web.login"))
        flash("Username taken", "error")
        return redirect(url_for("default_web.register"))
    return render_template("register.html", form=form)


@DEFAULT_WEB.route("/settings", methods=["GET", "POST"])
@login_required
def settings():
    handler = RssHandler()
    user_prefs = handler.get_user(session["logged_in"])
    form = SettingsForm(request.form, user_prefs)
    if request.method == "POST" and form.validate():
        if form.password.data.startswith("pbkdf2"):
            user_prefs.password = form.password.data
        else:
            user_prefs.password = generate_password_hash(
                form.password.data, method="pbkdf2:sha512"
            )
        user_prefs.api_key = form.api_key.data
        user_prefs.update_interval = form.update_interval.data
        handler.add_user(user_prefs)
        flash("Settings updated", "info")
        BACKGROUND_TASK.reschedule(session["logged_in"])
        return redirect(url_for("default_web.settings"))
    return render_template("settings.html", form=form)


import_thread = dict()


@DEFAULT_WEB.route("/import", methods=["GET", "POST"])
@login_required
def import_feeds():
    global import_thread

    form = ImportForm(CombinedMultiDict((request.form, request.files)))
    if request.method == "POST" and form.validate():
        if form.import_file.data.mimetype != "text/x-opml+xml":
            flash("Selected file is not OPML filetype", "error")
            return redirect(url_for("default_web.import_feeds"))
        import_thread[session["logged_in"]] = ImportThread(
            form.import_file.data, session["logged_in"]
        )
        import_thread[session["logged_in"]].start()
        flash("Import started", "info")
        return redirect(url_for("default_web.index"))

    try:
        is_thread_alive = import_thread[session["logged_in"]].isAlive()
    except KeyError:
        is_thread_alive = False
    except AttributeError:
        is_thread_alive = (
            True if import_thread[session["logged_in"]] is not None else False
        )

    if is_thread_alive:
        flash("Import in progress, please wait.", "error")
        return redirect(url_for("default_web.index"))
    else:
        return render_template("import_feeds.html", form=form)


@DEFAULT_WEB.route("/export", methods=["GET", "POST"])
@login_required
def export_feeds():
    form = ExportForm()
    if request.method == "POST" and form.validate():
        handler = RssHandler()
        feeds_list = handler.get_feeds(session["logged_in"])
        writer = OPMLWriter(feeds_list)
        return Response(
            writer.get_exported_feeds(),
            mimetype="text/xml",
            headers={

nnrss/templates/admin_panel.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Admin panel{% endblock %}</h2>
{% endblock %}

{% block content %}
<div class="col-md-10">
    <ul class="list-group list-group-flush">
	{% for user in users %}
	<li class="list-group-item text-center">
	    id:{{ user['id'] }}, name:{{ user['username'] }}, feeds:{{ feed_count[loop.index0] }}, admin:{{ user['is_admin'] }}, upd_interval:{{ user['update_interval'] }}
	</li>
	{% endfor %}
    </ul>
</div>
{% endblock %}

nnrss/templates/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#ffffff">
    <title>nano nano rss - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='font.css') }}">
    {% block more_css %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary justify-content-center">
	<a class="navbar-brand" href="/" >nano nano rss</a>
	<ul class="navbar-nav">
	    {% if session.logged_in %}
	    <li class="nav-item{%- if request.path == url_for('default_web.add_feed') %} active{% endif %}">
		<a href="{{ url_for('default_web.add_feed') }}" class="nav-link">Add</a>
	    </li>
	    <li class="nav-item{%- if request.path == url_for('default_web.feed_list') %} active{% endif %}">
		<a href="{{ url_for('default_web.feed_list') }}" class="nav-link">List</a>
	    </li>
	    <li class="nav-item{%- if request.path == url_for('default_web.settings') %} active{% endif %}">
		<a href="{{ url_for('default_web.settings') }}" class="nav-link">Settings</a>
	    </li>
	    <li class="nav-item{%- if request.path == url_for('default_web.import_feeds') %} active{% endif %}">
		<a href="{{ url_for('default_web.import_feeds') }}" class="nav-link">Import</a>
	    </li>
	    <li class="nav-item{%- if request.path == url_for('default_web.export_feeds') %} active{% endif %}">
		<a href="{{ url_for('default_web.export_feeds') }}" class="nav-link">Export</a>
	    </li>
	    <li class="nav-item">
		<a href="{{ url_for('default_web.logout') }}" class="nav-link">Log Out</a>
	    </li>
	    {% else %}
	    <li class="nav-item{%- if request.path == url_for('default_web.register') %} active{% endif %}">
		<a href="{{ url_for('default_web.register') }}" class="nav-link">Register</a>
	    </li>
	    <li class="nav-item{%- if request.path == url_for('default_web.login') %} active{% endif %}">
		<a href="{{ url_for('default_web.login') }}" class="nav-link">Log In</a>
	    </li>
	    {% endif %}
	</ul>
    </nav>
    <div class="container pt-3">
	<div class="text-center pb-3">
	    {% block header %}{% endblock %}
	    {% block subtitle %}{% endblock %}
	</div>
	{% with messages = get_flashed_messages(with_categories=True) %}
	    {% if messages %}
		{% for category, message in messages %}
		    {% if category == 'info' %}
			<div class="alert alert-success">{{ message }}</div>
		    {% elif category == 'error' %}
			<div class="alert alert-danger">{{ message }}</div>
		    {% endif %}
		{% endfor %}
	    {% endif %}
	{% endwith %}
	<div class="row justify-content-center">
	    {% block content %}{% endblock %}
	</div>
    </div>
    <footer class="pb-2">
	{% block footer %}{% endblock %}
    </footer>
</body>
</html>

nnrss/templates/delete_confirm.html
{% extends 'base.html' %}

{% block header %}
<h2 class="text-center">{% block title %}Delete {{ the_feed['title'] }}?{% endblock %}</h2>
{% endblock %}

{% block content %}
<div class="container">
    <h5 class="text-center">Do you really want to delete feed <a href="{{ the_feed['link'] }}">{{ the_feed['link'] }}</a>?</h2>
    <div class="row justify-content-md-center">
	<div class="btn-group">
	    <form method="post" action="{{request.path}}">
		<input class="btn btn-danger mx-2 mb-2" type="submit" value="Yes">
	    </form>
	    <form method="get" action="{{ request.path.split('/remove')[0] }}">
		<input class="btn btn-primary mx-2 mb-2" type="submit" value="No">
	    </form>
	</div>
    </div>
</div>
{% endblock %}

nnrss/templates/entries_list.html
{% extends 'base.html' %}

{% block header %}
<h2 class="text-center">{% block title %}{{ feed['title'] }}{% endblock %}</h2>
<h5 class="text-center"><a href="{{ feed['link'] }}">{{ feed['link'] }}</a></h2>
{% endblock %}

{% block content %}
<div class="btn-group">
    <form method="get" action="{{request.path}}/unread">
	<input class="btn btn-secondary mx-2 mb-2" type="submit" value="Show only unread">
    </form>
    <form method="post" action="{{request.path}}/update">
	<input class="btn btn-primary mx-2 mb-2" type="submit" value="Update feed">
    </form>
    <form method="get" action="{{request.path}}/remove">
	<input class="btn btn-danger mx-2 mb-2" type="submit" value="Remove feed">
    </form>
</div>
<div class="col-md-10 pt-3">
    <ul class="list-group list-group-flush">
	{% for item in entries.items %}
	    {% if item.is_read %}
	    <li class="list-group-item">
		<div class="row">
		    <a href="{{item.link}}" class="col-8">{{item.title}}</a> 
		    <div class="col text-right" >{{item.date}}</div>
		</div>
	    </li>
	    {% else %}
	    <li class="list-group-item bg-light">
		<div class="row">
		    <a class="col-8" href="{{request.path}}/set_read?entry_id={{item.id}}">{{item.title}}</a> 
		    <div class="col text-right">{{item.date}}</div>
		</div>
	    </li>
	    {% endif %}
	{% endfor %}
    </ul>
{% endblock %}
{% block footer %}
    {% from "macros/renderpagination.html" import render_pagination %}
    {{ render_pagination("default_web.view_feed_entries", feed, entries) }}
{% endblock %}

nnrss/templates/export_feeds.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Export feeds{% endblock %}</h2>
{% endblock %}

{% block content %}
{% from "macros/renderfield.html" import render_field %}
<div class="col-md-5">
    <form method="post">
	    {{ render_field(form.export_button, class_="btn btn-secondary") }}
    </form>
</div>
{% endblock %}

nnrss/templates/feed_add.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Add feed{% endblock %}</h2>
{% endblock %}

{% block content %}
{% from "macros/renderfield.html" import render_field %}
<div class="col-md-5">
    <form method="post">
	<div class="form-group">
	    {{ render_field(form.url, class="form-control") }}
	</div>
	<div class="form-group">
	    {{ render_field(form.category, class_="form-control") }}
	</div>
	<input type="submit" class="btn btn-primary" value="Add feed">
    </form>
</div>
{% endblock %}

nnrss/templates/feed_list.html
{% extends 'base.html' %}

{% block more_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='checkbox_hide.css') }}">
{% endblock %}

{% block header %}
<h2>{% block title %}Feed list{% endblock %}</h2>
{% endblock %}

{% block subtitle %}
{% if category_name %}
    <h4>Category: {{ category_name }}</h4>
{% else %}
    <h4>All feeds</h4>
{% endif %}
{% endblock %}

{% block content %}
{% if categories %}
<div class="col-md-8 text-center">
    <input id="checkbox_categories" class="form-check-input mb-2" type="checkbox">
    <label class="form-check-label" for="checkbox_categories">Show categories</label>
    <div id="hide" class="d-flex flex-wrap justify-content-center">
	{% for category in categories %}
	    <a class="p-2 m-1 bg-light rounded" href="?category={{ category.name }}">{{ category.name }}</a>
	{% endfor %}
    </div>
</div>
{% endif %}
<div class="col-md-10">
    <ul class="list-group list-group-flush">
	{% for item in feeds %}
	{% if item['changed'] %}
	<h5 class="mt-2">{{ item['category'] }}</h5>
	{% endif %}
	<li class="list-group-item text-center">
	    <a href="/feed/{{ item['id'] }}">{{ item['title'] + ' - ' + item['link'] }}</a>
	</li>
	{% endfor %}
    </ul>
</div>
{% endblock %}

nnrss/templates/import_feeds.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Import{% endblock %}</h2>
{% endblock %}

{% block content %}
{% from "macros/renderfield.html" import render_field %}
<div class="col-md-5">
    <form enctype="multipart/form-data" method="post">
	    <div class="form-group">
		{{ render_field(form.import_file, class_="form-control-file") }}
	    </div>
	<input type="submit" class="btn btn-primary" value="Import">
    </form>
</div>
{% endblock %}

nnrss/templates/login.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Login{% endblock %}</h2>
{% endblock %}

{% block content %}
{% from "macros/renderfield.html" import render_field %}
<div class="col-md-5">
    <form method="post">
	<div class="form-group">
	    {{ render_field(form.username, class_="form-control") }}
	</div>
	<div class="form-group">
	    {{ render_field(form.password, class_="form-control") }}
	</div>
	<input type="submit" class="btn btn-primary" value=Login>
    </form>
</div>
{% endblock %}

nnrss/templates/message_box.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Feed added{% endblock %}</h2>
{% endblock %}

{% block content %}
<h3>Feed {{ feed_name }} added.</h3>
{% endblock %}

nnrss/templates/register.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Register your account{% endblock %}</h2>
{% endblock %}

{% block content %}
{% from "macros/renderfield.html" import render_field %}
<div class="col-md-5">
    <form method="post">
	<div class="form-group">
	    {{ render_field(form.username, class_="form-control") }}
	</div>
	<div class="form-group">
	    {{ render_field(form.password, class_="form-control") }}
	</div>
	<div class="form-group">
	    {{ render_field(form.confirm, class_="form-control") }}
	</div>
	<input type=submit class="btn btn-primary" value=Register>
    </form>
</div>
{% endblock %}

nnrss/templates/remove_feed.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Feed deletion confirmation{% endblock %}</h2>
{% endblock %}

{% block content %}
<h3>Are you sure you want to feed {{ feed_name }} ?</h3>
<form method="post" action="{{request.path}}/remove">
    <p><input type="submit" value="Remove">
</form>
{% endblock %}

nnrss/templates/settings.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Settings{% endblock %}</h2>
{% endblock %}

{% block content %}
{% from "macros/renderfield.html" import render_field %}
<div class="col-md-5">
    <form method="post">
	<div class="form-group">
	    {{ render_field(form.password, class_="form-control") }}
	</div>
	<div class="form-group">
	   {{ render_field(form.api_key, class_="form-control") }}
	</div>
	<div class="form-group">
	   {{ render_field(form.update_interval, class_="form-control") }}
	</div>
	<input type="submit" class="btn btn-primary" value="Update">
    </form>
</div>
{% endblock %}

nnrss/templates/unread_entries.html
{% extends 'base.html' %}

{% block more_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='checkbox_hide.css') }}">
{% endblock %}

{% block header %}
<h2>{% block title %}Unread entries{% endblock %}</h2>
{% endblock %}

{% block subtitle %}
{% if category_name %}
    <h4>Category: {{ category_name }}</h4>
{% else %}
    <h4>All feeds</h4>
{% endif %}
{% endblock %}

{% block content %}
{% if categories %}
<div class="col-md-8 text-center">
    <input id="checkbox_categories" class="form-check-input mb-2" type="checkbox">
    <label class="form-check-label" for="checkbox_categories">Show categories</label>
    <div id="hide" class="d-flex flex-wrap justify-content-center">
	{% for category in categories %}
	    <a class="p-2 m-1 bg-light rounded" href="?category={{ category.name }}">{{ category.name }}</a>
	{% endfor %}
    </div>
</div>
{% endif %}
<div class="col-md-10">
    <ul class="list-group list-group-flush">
	{% for item in entries %}
	<li class="list-group-item text-center">
	    <a class="col-8" href="{{request.url_root}}feed/{{item.id_feed}}/set_read?entry_id={{item.id}}">{{item.title}} - {{item.feed.link}}</a> {{ item.date }}
	</li>
	{% endfor %}
    </ul>
</div>
{% endblock %}